"""Concatenate EVERY .py source file in the project into ONE file, each section under a
`# ===== FILE: <relpath> =====` header, preceded by a table of contents. This is a complete,
human-readable single-file archive of all the code (not a single importable module — a 281-file
interdependent project cannot be merged into one module without name clashes)."""
import os
import sys

ROOT = sys.argv[1] if len(sys.argv) > 1 else "."
OUT = sys.argv[2] if len(sys.argv) > 2 else "projectharan_all_code.py"

SKIP_DIRS = {".git", "__pycache__", ".venv", "venv", "node_modules", "site-packages", ".pytest_cache", ".mypy_cache"}

paths = []
for dirpath, dirnames, filenames in os.walk(ROOT):
    dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
    for fn in filenames:
        if fn.endswith(".py"):
            rel = os.path.relpath(os.path.join(dirpath, fn), ROOT)
            paths.append(rel)

# top-level files first (no os.sep), then nested — each group alphabetical
paths.sort(key=lambda p: (p.count(os.sep), p))

# don't bundle the bundler itself or its output
paths = [p for p in paths if os.path.basename(p) not in (os.path.basename(__file__), os.path.basename(OUT))]

records = []
total_lines = 0
for rel in paths:
    try:
        with open(os.path.join(ROOT, rel), "r", encoding="utf-8", errors="replace") as f:
            src = f.read()
    except Exception as e:  # noqa: BLE001
        src = f"# <<could not read: {type(e).__name__}: {e}>>\n"
    nlines = src.count("\n") + 1
    total_lines += nlines
    records.append((rel, nlines, src))

BAR = "=" * 110
parts = []
parts.append(f'''"""
PROJECTHARAN — COMPLETE SINGLE-FILE SOURCE ARCHIVE
{BAR}
Every .py source file in the project, concatenated into ONE file. {len(records)} files, {total_lines:,} lines.

This is a READABLE ARCHIVE, not a single importable module: a {len(records)}-file interdependent project cannot be
merged into one runnable module (duplicate imports, `from __future__` placement, name clashes). Each original file is
reproduced verbatim below under a `# ===== FILE: <relpath> =====` header. To run the project, split it back to the
original tree (the headers give every path) or use the original repo.

Generated by bundle_all_code.py — regenerate with:  python3 bundle_all_code.py . projectharan_all_code.py
{BAR}

TABLE OF CONTENTS ({len(records)} files):
''')
for i, (rel, nlines, _src) in enumerate(records, 1):
    parts.append(f"  {i:3d}. {rel}  ({nlines} lines)\n")
parts.append(f'{BAR}\n"""\n')

for rel, nlines, src in records:
    parts.append(f"\n\n# {BAR}\n# ===== FILE: {rel}  ({nlines} lines) =====\n# {BAR}\n\n")
    parts.append(src)
    if not src.endswith("\n"):
        parts.append("\n")

blob = "".join(parts)
with open(OUT, "w", encoding="utf-8") as f:
    f.write(blob)
print(f"wrote {OUT}: {len(records)} files, {total_lines:,} source lines, {len(blob):,} bytes "
      f"({blob.count(chr(10))+1:,} total lines)")
