"""
Generate MATH_SHOWCASE.md from REAL solver runs (no hand-edited results). Each entry shows the input, the grade,
the answer, the certificate, and the visible reasoning trace — a measured demonstration of the MATH arsenal.
Run: python3 scripts/gen_math_showcase.py
"""
from __future__ import annotations

import os
import sys

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _ROOT)                                    # make mathmode/ importable regardless of cwd

import sympy as sp

from mathmode import solver as S
import kernel_verdict as KV

x = sp.Symbol("x")

# (heading, input-as-typed-or-dict) — a diverse tour across the 16 families; free-text where natural.
SHOWCASE = [
    ("Power sum (fold → Faulhaber, ∀n)", {"fold": {"kind": "power_sum", "p": 3}}),
    ("Hypergeometric sum (broth O(1))", "sum: k**2*2**k"),
    ("Hypergeometric sum (broth miss → Gosper)", "sum: k**6*2**k"),
    ("No closed form (honest DECLINE)", "sum: 1/k"),
    ("Primality (deterministic proof)", "is 2147483647 prime"),
    ("Factorization", "factorize 360"),
    ("Pell's equation x²−61y²=1", "pell 61"),
    ("Discrete log", {"domain": "number_theory", "op": "discrete_log", "g": 2, "h": 22, "m": 29}),
    ("Modular √ (Tonelli–Shanks)", {"domain": "number_theory", "op": "modular_sqrt", "a": 10, "p": 13}),
    ("Exact linear solve (residual=0)", {"domain": "linear_algebra", "op": "solve",
                                         "A": [[2, 1, -1], [-3, -1, 2], [-2, 1, 2]], "b": [8, -11, -3]}),
    ("Eigenvalues (A·v=λ·v)", {"domain": "linear_algebra", "op": "eigen", "A": [[2, 1], [1, 2]]}),
    ("Factor a polynomial", "factor x^4-1"),
    ("Roots (radical, verified)", "solve x^3-2"),
    ("Quintic with no radicals (DECLINE)", {"domain": "algebra", "op": "solve_poly", "poly": x ** 5 - x + 1}),
    ("Lagrange interpolation", {"domain": "algebra", "op": "interpolate", "points": [(0, 0), (1, 1), (2, 4)]}),
    ("Partial fractions", {"domain": "algebra", "op": "partial_fractions", "expr": 1 / (x ** 2 - 1)}),
    ("Symbolic integral (diff-verified)", "integrate x^2"),
    ("No elementary antiderivative (DECLINE)", {"domain": "calculus", "op": "integrate", "f": x ** x}),
    ("Taylor series of eˣ", {"domain": "calculus", "op": "taylor", "f": sp.exp(x), "a": 0, "n": 5}),
    ("Sturm real-root count", {"domain": "certified_numeric", "op": "root_count", "poly": x ** 3 - x, "a": -2, "b": 2}),
    ("√2 exact enclosure", {"domain": "certified_numeric", "op": "sqrt", "n": 2}),
    ("Monte-Carlo π (PROBABILISTIC ε,δ)", {"domain": "certified_numeric", "op": "montecarlo_pi",
                                           "samples": 60000, "delta": 1e-2}),
    ("Linear program (strong duality)", {"domain": "optimization", "op": "lp_max",
                                         "c": [3, 2], "A": [[1, 1], [1, 3]], "b": [4, 6]}),
    ("Dimensional check E=½mv²", {"domain": "science_engineering", "op": "dimension_check",
                                  "equation": "E = m*v**2", "binding": {"E": "energy", "m": "mass", "v": "velocity"}}),
    ("Wrong formula E=mv (DECLINE)", {"domain": "science_engineering", "op": "dimension_check",
                                      "equation": "E = m*v", "binding": {"E": "energy", "m": "mass", "v": "velocity"}}),
    ("Markov bound (proven)", {"domain": "probability", "op": "markov", "mean": 3, "a": 10}),
    ("Polynomial nonnegativity", "x^2+1 >= 0"),
    ("Not nonnegative (counterexample)", {"domain": "inequalities", "op": "nonneg", "poly": x ** 2 - 1}),
    ("ODE y″+y=0 (back-substituted)", {"domain": "differential", "op": "ode",
                                       "ode": sp.Eq(sp.Function("y")(x).diff(x, 2) + sp.Function("y")(x), 0)}),
    ("Shortest path (optimality cert)", {"domain": "graph", "op": "shortest_path", "n": 3,
                                         "edges": [[0, 1, 2], [1, 2, 3], [0, 2, 10]], "source": 0}),
    ("Bipartite? triangle (odd cycle)", {"domain": "graph", "op": "bipartite", "n": 3,
                                         "edges": [[0, 1], [1, 2], [2, 0]]}),
    ("ζ(2) = π²/6 (Euler)", "zeta(2)"),
    ("Γ(5/2) = 3√π/4", "gamma(5/2)"),
    ("Taylor of eˣ (order 5)", {"domain": "calculus", "op": "taylor", "f": sp.exp(x), "a": 0, "n": 5}),
    ("De Morgan tautology (Z3)", {"domain": "logic", "op": "tautology",
                                  "formula": sp.Equivalent(~(sp.Symbol("a") & sp.Symbol("b")),
                                                           ~sp.Symbol("a") | ~sp.Symbol("b"))}),
    ("a∧¬a unsatisfiable (Z3 proof)", {"domain": "logic", "op": "satisfiable",
                                       "formula": sp.Symbol("a") & ~sp.Symbol("a")}),
]

_KO = {KV.EXACT: "EXACT", KV.PROBABILISTIC: "PROBABILISTIC", KV.DECLINE: "DECLINE"}


def main():
    out = ["# MATH-SHOWCASE — the arsenal, on real problems",
           "",
           "*Generated by `scripts/gen_math_showcase.py` from REAL `mathmode.solver` runs — no hand-edited "
           "results. Each entry shows the grade, the answer, the machine-checked certificate, and the visible "
           "reasoning trace. DECLINEs are correct behaviour (no closed form / not true / unprovable), never "
           "failures. Reproduce by running the script.*", ""]
    counts = {KV.EXACT: 0, KV.PROBABILISTIC: 0, KV.DECLINE: 0}
    for title, prob in SHOWCASE:
        sol = S.solve_in_mode(prob, "normal")
        v = sol.verdict
        counts[v.status] = counts.get(v.status, 0) + 1
        out.append(f"### {title}")
        shown = prob if isinstance(prob, str) else (prob.get("op") or prob.get("fold") or prob)
        out.append(f"- **input**: `{shown}`")
        out.append(f"- **grade**: **{_KO.get(v.status, v.status)}**")
        if v.status != KV.DECLINE:
            ans = sol.to_dict()["answer"]
            out.append(f"- **answer**: `{ans[:160]}`")
            c = v.certificate
            extra = (f" · ε={float(c.epsilon):.4f}" if c.epsilon is not None else "") + \
                    (f" · δ={float(c.delta)}" if c.delta is not None else "")
            out.append(f"- **certificate** (`{c.kind}`): {c.detail}{extra}")
        else:
            out.append(f"- **reason**: {v.reason}")
        out.append("")
    head = (f"**{len(SHOWCASE)} problems** · EXACT {counts[KV.EXACT]} · PROBABILISTIC "
            f"{counts[KV.PROBABILISTIC]} · DECLINE {counts[KV.DECLINE]} (each DECLINE is the honest, correct answer).")
    out.insert(4, head)
    out.insert(5, "")
    open(os.path.join(_ROOT, "MATH_SHOWCASE.md"), "w", encoding="utf-8").write("\n".join(out))
    print(head)
    print("wrote MATH_SHOWCASE.md")


if __name__ == "__main__":
    main()
